### ISSUE TITLE
Crash when installing, not sure why

### ISSUE THREAD

**Issue by obsidianart** [sethvincent/generator-ghost#11] opened 2015-07-06 14:46 UTC
after normal generator crash I replicate the message running grunt --verbose, here's the output. We tried in 3 different machines, the problem is the same in all of them. I don't know how to continue but if you have any suggestion I will try (mac machine, last operating system, node 0.12.4, I changed the full path with *)

Registering "grunt-update-submodules" local Npm module tasks.
Reading ***/node_modules/grunt-update-submodules/package.json...OK
Parsing ***/node_modules/grunt-update-submodules/package.json...OK
Loading "update-submodules.js" tasks...OK
+ update_submodules
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ assets, buildAboutPage, cleanDatabase, coverage, default, dev, docs, ensureConfig, help, init, lint, master-warn, prod, release, setTestEnv, spawnCasperJS, test, test-all, test-functional, test-functional-setup, test-integration, test-module, test-routes, test-setup, test-unit, testem, validate

No tasks specified, running default tasks.
Running tasks: default

Running "default" task

Running "shell:ember:dev" (shell) task
Verifying property shell.ember exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, execOptions={"cwd":"***/core/client","stdout":false}
Command: ***/core/client/node_modules/.bin/ember build
Warning: spawn /bin/sh ENOENT Use --force to continue.

**Comment by bpompea** [comment] 2015-07-18 22:16
I'm having the same issue. I ran grunt init and it worked just fine. 
<img width="659" alt="screen shot 2015-07-18 at 4 15 28 pm" src="https://cloud.githubusercontent.com/assets/5150547/8763713/60740e3c-2d68-11e5-8de9-a7127780055e.png">

**Comment by acburdine** [comment] 2015-07-19 17:16
There's an issue with the generator because it hasn't been updated to support the latest Ghost grunt setup. I was working on a fix/update for a while, then dropped it because I had to finish some other things – I'll try and see if I can finish it soon.

Also, #10 also details the same issue.

**Comment by pdougall1** [comment] 2016-02-20 18:45
Is this issue resolved?  I'm having the same trouble after cloning the ghost repo given from the DigitalOcean single click droplet.  That image might be using an old version maybe?

**Comment by acburdine** [comment] 2016-05-17 18:44
@pdougall1 the DigitalOcean single click droplet doesn't use the Ghost repository. It uses the built zip file which is intended for production usage, and thus it doesn't have the Gruntfile which is necessary to run those commands.

**Comment by acburdine** [comment] 2016-05-18 04:12
Closing as a duplicate of #10

**Closed by acburdine** 2016-05-18 04:12 UTC
